### ISSUE TITLE
Fix Scroll

### ISSUE THREAD

**Issue by uisendy** [AnietieAkpanumoh/Rotating-navigation#1]
## My Review ✅ ✅ ✅ 

@AnietieAkpanumoh Awesome and lovely project. very dynamic and beautiful to use. The UI is top-notch and innovative. 🚀 🚀 

## Optional suggestions

However, this is just a minor suggestion, and I noticed that after clicking the menu, the scroll is still active, This can be corrected by creating a class maybe ".noScroll" and setting the overflow for the container to be "Hidden" and activated during the click event for the Menu. 

This is a very cool navigation menu. 

 ![image](https://user-images.githubusercontent.com/95294594/189357743-67d5fddf-697e-4584-a5f1-3c80e3c83b94.png)

**Comment by AnietieAkpanumoh** [comment]
Thank you for the suggestion. The suggestion has been adopted and issue fixed. The scrollbar is hidden on the y-axis when the navigation menu is clicked.
